# Generated by Django 2.2.19 on 2021-03-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_downvote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='detail',
        ),
    ]
